### PR TITLE
Now 'dry run' is default mode. To prevent accidental mistakes.

### PR DESCRIPTION
**Pull request by AlexKVal**
to prevent such things https://github.com/react-bootstrap/react-bootstrap/pull/1325#issuecomment-140853722

### CODE REVIEW

**Comment by jquense** [comment]
hey! thanks for all the recent work on this. Could we maybe make that default configurable? I understand the reason for such a default but its counter to how shell scripts work for almost everything else. Having to type the additional --run for 90% of the times I am running this is a bit annoying

**Comment by AlexKVal** [comment]
No problem. I agree that it is counter to all other scripts, but this is exactly the feature :smile: 
We release software very rare. And time goes - we forget about those `--` gouble dashes or smth else.

I've made it such way that it reminds about "--run" option:
screen shot 2015-09-17 at 9 55 59 am

you instantly press `Ctrl+C`, `arrow up` add `--run` and press `Enter` :wink: 

If you still think with all of my arguments :stuck_out_tongue_winking_eye: that "--dry-run" option and configurable default behavior are needed, I will add them to `release-script` :cherries: 

What do you think ?

**Comment by jquense** [comment]
I still find the default counter intuitive, the script if for releasing, not for seeing if a release would work. Git also has a dry-run mode, but that isn't the default for a reason, it would be really hard to work with if it did. I am almost always running the script to release my module so I usually expect that to be the default behavior. Forgetting, having to ctrl-c, arrow up and type --run is pretty bad UX, when I should just be able to type the command. If people want safety then the general procedure is to alias the command with --dry-run always on, but I wouldn't make it the default. 

:) I do appreciate the attempt to try and prevent mistakes, but in this case I think its over prescriptive and ends up not actually being helpful most of the time. Especially since if you accidentally release it really isn't that hard to undo do it.

**Comment by AlexKVal** [comment]
Heh. Ok ok :smile: 

Then what is the best way to address it in `release-script` you think ?

I would prefer to leave it as a feature of `release-script` to run in "dry run" mode by default.

Then it seems I need to add option smth like that: `"defaultDryRun": "false"` ?

**Comment by AlexKVal** [comment]
And then what do you think about https://github.com/react-bootstrap/react-prop-types/pull/16 ?
It seems that PR is superfluos. Close it ? Or wait others to say their opinions ?

**Comment by jquense** [comment]
that can be up to others since I don't usually work on that project :)

**Comment by AlexKVal** [comment]
But you don't mind about `"defaultDryRun": "false"` option in `package.json` then ?

**Comment by jquense** [comment]
sure seems fine :) I'd of course prefer that the default be `false` as well, but it is your project so I bow to whatever you think is the best default. I am happy as long as I can configure it at least

**Comment by AlexKVal** [comment]
Ok then. I'll add it :cherries: 

## 

Truth is I am also made those `accidental` publishings... and worse of that, they were partial..
I did forget to add `bower` option and it had released only `npm` package.
The next patch version has been with empty changelog because I still needed to publish `bower` version.

Then I did forget to add GitHub Token in my console after reboot :smile: 
And again I had to fix it manually.

That is my main motivation for such haste to add and release "dry run" default mode.
@taion by that comment has nudged my thoughts :smile:

**Comment by taion** [comment]
Thinking about this a bit more, I agree w/@jquense - I think it'd be really valuable to make these scripts be able to default to dry runs, but that the default setting for this config option should probably be to release, just to make things as straightforward as possible.

We'd probably want to configure things to go through dry runs, but one extra line of config seems like not too big a deal.

**Comment by AlexKVal** [comment]
Would it be too much if I then reverse 'defaultDryMode' to 'actual run' (as it was before) in the next minor `release-script@0.6.0` version ?
And it will be with this new `defaultDryMode` option set to `false` by default, but will be documented
for those who wish to change default behavior.
While now there are a very little projects / users of `r-script` I presume it woun't be too much deal ?

What do you think guys ?

## 

And second question: I presume I could safely just close these two PRs ?
https://github.com/react-bootstrap/react-bootstrap/pull/1329
https://github.com/react-bootstrap/react-prop-types/pull/16

**Comment by AlexKVal** [comment]
Or I can leave `defaultDryRun` mode as `true` and just change those two PR's with adding:

``` json
"release-script" : {
  "defaultDryRun": "false"
}
```

?

**Comment by taion** [comment]
I'm not sure I understand. I think we should just change https://github.com/AlexKVal/release-script/commit/136c51106d445f2eeca5f38201ff449265b77901#diff-a1ca48439c82c10c6224f7c126531cf8R52 to do `=== true`. I think it'd be nice to have this option enabled for React-Bootstrap because I'm afraid of accidentally publishing.

**Comment by AlexKVal** [comment]
> I think it'd be nice to have this option enabled for React-Bootstrap because I'm afraid of accidentally publishing.

Then just merge https://github.com/react-bootstrap/react-bootstrap/pull/1329 as is :wink: 
It is exactly for your case.
"Dry-run" mode by default.
You have to add `--run` when you are ready to actually release `React-Bootstrap`.

And then I propose to merge https://github.com/react-bootstrap/react-prop-types/pull/16 too.
It will have "dry-run" mode by default too.

**Comment by taion** [comment]
Okay - we'll make a note to upgrade again once you have a new release.

**Comment by AlexKVal** [comment]
For posterity: (from my private gitter chat with @taion)

> I've decided to leave it now with `dry run` mode by default.
> If in the future this will be an issue for new users - they will write about it and write a lot :smile: 
> And then I always can switch default mode other way.

:cherries:

**Comment by mjhasbach** [comment]
I also agree that dry run should not be the default.

**Comment by AlexKVal** [comment]
Ok then. It seems I should change the default mode :sparkle: 
Probably I should release it as a major version change. In this case 1.0.0.

**Comment by AlexKVal** [comment]
[Version 1.0.0](https://github.com/AlexKVal/release-script/releases/tag/v1.0.0) is out.

**Comment by taion** [comment]
Interesting – you didn't want to leave the option and just change the default?

**Comment by AlexKVal** [comment]
I thought (from that discussion) that nobody needs the "defaultDryRun" option in `package.json` so I totally removed it.
Do you think it is worth it to leave it ?

**Comment by taion** [comment]
I think it's a valuable option. I'd turn it on for e.g. React-Bootstrap. I don't think it should be the default, though.

**Comment by AlexKVal** [comment]
O.. I see. Ok then I'll put it back :+1: 
Thank you for pointing to it out :sparkle:

**Comment by AlexKVal** [comment]
I have put it back #39 :blush: 
[v1.0.1](https://github.com/AlexKVal/release-script/releases/tag/v1.0.1)

**Comment by taion** [comment]
Shouldn't this be 1.1.0, since it's a new(-ish) feature? :laughing:

**Comment by AlexKVal** [comment]
I decided to use `patch` because in the reality the feature was absent for a couple of hours :laughing: 
and there is no breaking changes after `1.0.0` introduced by it.

Though I admit that I should have used
`MINOR version when you add functionality in a backwards-compatible manner` (http://semver.org/) probably.
It is my first `MAJOR` release ever, bear with me. :blush:

**Pull request merged**
